import { Mini } from "../types";
import { getTalentsForMini } from "./talents";

type MiniId = keyof typeof names;

export const minis = {
  AngryChickens: 0x01,
  ArcaneBlast: 0x02,
  Blizzard: 0x03,
  ChainLightning: 0x04,
  CheatDeath: 0x05,
  DeepBreath: 0x06,
  EarthAndMoon: 0x07,
  Eclipse: 0x08,
  Execute: 0x09,
  HolyNova: 0x0a,
  LivingBomb: 0x0b,
  Polymorph: 0x0c,
  SmokeBomb: 0x0d,
  Abomination: 0x0e,
  AncientOfWar: 0x0f,
  AnubArak: 0x10,
  Banshee: 0x11,
  BaronRivendare: 0x12,
  BatRider: 0x13,
  BloodmageThalnos: 0x14,
  BogBeast: 0x15,
  CairneBloodhoof: 0x16,
  Cenarius: 0x17,
  CharlgaRazorflank: 0x18,
  Chimaera: 0x19,
  CoreHounds: 0x1a,
  DarkIronMiner: 0x1b,
  DarkspearTroll: 0x1c,
  DefiasBandits: 0x1d,
  DireBatlings: 0x1e,
  OrgrimDoomhammer: 0x1f,
  Drake: 0x20,
  GeneralDrakkisath: 0x21,
  DruidOfTheClaw: 0x22,
  Dryad: 0x23,
  EarthElemental: 0x24,
  EmperorThaurissan: 0x25,
  FaerieDragon: 0x26,
  FireElemental: 0x27,
  Firehammer: 0x28,
  Flamewaker: 0x29,
  FrostwolfShaman: 0x4b,
  GnollBrute: 0x2d,
  GrommashHellscream: 0x30,
  Harpies: 0x32,
  Footmen: 0x2a,
  Gargoyle: 0x2b,
  Ghoul: 0x2c,
  SafePilot: 0x2e,
  GoblinSappers: 0x2f,
  GryphonRider: 0x31,
  HarvestGolem: 0x33,
  HeadlessHorseman: 0x34,
  Hogger: 0x35,
  Huntress: 0x36,
  JainaProudmoore: 0x37,
  MaievShadowsong: 0x38,
  MalfurionStormrage: 0x39,
  MeatWagon: 0x3a,
  MoltenGiant: 0x3b,
  Moonkin: 0x3c,
  Mountaineer: 0x3d,
  MurlocTidehunters: 0x3f,
  Necromancer: 0x40,
  OgreMage: 0x41,
  OldMurkEye: 0x42,
  OnuAncientOfLore: 0x43,
  PlagueFarmer: 0x44,
  Prowler: 0x45,
  Pyromancer: 0x46,
  Quillboar: 0x47,
  Ragnaros: 0x48,
  Raptors: 0x49,
  RendBlackhand: 0x4a,
  SkeletonParty: 0x4c,
  Skeletons: 0x4d,
  Sneed: 0x4e,
  Spiderlings: 0x4f,
  StonehoofTauren: 0x50,
  SwoleTroll: 0x51,
  SylvanasWindrunner: 0x52,
  TirionFordring: 0x53,
  Treant: 0x54,
  Vultures: 0x55,
  WarsongGrunts: 0x56,
  WarsongRaider: 0x57,
  WhelpEggs: 0x58,
  WitchDoctor: 0x59,
  Worgen: 0x5a,
  YseraTheDreamer: 0x5b,
  Priestess: 0x5d,
  ArthasMenethil: 0x5e,
} as const;

const names = {
  [minis.AngryChickens]: "Angry Chickens",
  [minis.ArcaneBlast]: "Arcane Blast",
  [minis.Blizzard]: "Blizzard",
  [minis.ChainLightning]: "Chain Lightning",
  [minis.CheatDeath]: "Cheat Death",
  [minis.DeepBreath]: "Deep Breath",
  [minis.EarthAndMoon]: "Earth And Moon",
  [minis.Eclipse]: "Eclipse",
  [minis.Execute]: "Execute",
  [minis.HolyNova]: "Holy Nova",
  [minis.LivingBomb]: "Living Bomb",
  [minis.Polymorph]: "Polymorph",
  [minis.SmokeBomb]: "Smoke Bomb",
  [minis.Abomination]: "Abomination",
  [minis.AncientOfWar]: "Ancient Of War",
  [minis.AnubArak]: "Anub'Arak",
  [minis.Banshee]: "Banshee",
  [minis.BaronRivendare]: "Baron Rivendare",
  [minis.BatRider]: "Bat Rider",
  [minis.BloodmageThalnos]: "Bloodmage Thalnos",
  [minis.BogBeast]: "Bog Beast",
  [minis.CairneBloodhoof]: "Cairne Bloodhoof",
  [minis.Cenarius]: "Cenarius",
  [minis.CharlgaRazorflank]: "Charlga Razorflank",
  [minis.Chimaera]: "Chimaera",
  [minis.CoreHounds]: "Core Hounds",
  [minis.DarkIronMiner]: "Dark Iron Miner",
  [minis.DarkspearTroll]: "Darkspear Troll",
  [minis.DefiasBandits]: "Defias Bandits",
  [minis.DireBatlings]: "Dire Batlings",
  [minis.OrgrimDoomhammer]: "Orgrim Doomhammer",
  [minis.Drake]: "Drake",
  [minis.GeneralDrakkisath]: "General Drakkisath",
  [minis.DruidOfTheClaw]: "Druid Of The Claw",
  [minis.Dryad]: "Dryad",
  [minis.EarthElemental]: "Earth Elemental",
  [minis.EmperorThaurissan]: "Emperor Thaurissan",
  [minis.FaerieDragon]: "Faerie Dragon",
  [minis.FireElemental]: "Fire Elemental",
  [minis.Firehammer]: "Firehammer",
  [minis.Flamewaker]: "Flamewaker",
  [minis.GnollBrute]: "Gnoll Brute",
  [minis.GrommashHellscream]: "Grommash Hellscream",
  [minis.Harpies]: "Harpies",
  [minis.Footmen]: "Footmen",
  [minis.FrostwolfShaman]: "Frostwolf Shaman",
  [minis.Gargoyle]: "Gargoyle",
  [minis.Ghoul]: "Ghoul",
  [minis.SafePilot]: "S.A.F.E. Pilot",
  [minis.GoblinSappers]: "Goblin Sappers",
  [minis.GryphonRider]: "Gryphon Rider",
  [minis.HarvestGolem]: "Harvest Golem",
  [minis.HeadlessHorseman]: "Headless Horseman",
  [minis.Hogger]: "Hogger",
  [minis.Huntress]: "Huntress",
  [minis.JainaProudmoore]: "Jaina Proudmoore",
  [minis.MaievShadowsong]: "Maiev Shadowsong",
  [minis.MalfurionStormrage]: "Malfurion Stormrage",
  [minis.MeatWagon]: "Meatwagon",
  [minis.MoltenGiant]: "Molten Giant",
  [minis.Moonkin]: "Moonkin",
  [minis.Mountaineer]: "Mountaineer",
  [minis.MurlocTidehunters]: "Murloc Tidehunters",
  [minis.Necromancer]: "Necromancer",
  [minis.OgreMage]: "Ogre Mage",
  [minis.OldMurkEye]: "Old Murk-Eye",
  [minis.OnuAncientOfLore]: "Onu, Ancient of Lore",
  [minis.PlagueFarmer]: "Plague Farmer",
  [minis.Prowler]: "Prowler",
  [minis.Pyromancer]: "Pyromancer",
  [minis.Quillboar]: "Quillboar",
  [minis.Ragnaros]: "Ragnaros",
  [minis.Raptors]: "Raptors",
  [minis.RendBlackhand]: "Rend Blackhand",
  [minis.SkeletonParty]: "Skeleton Party",
  [minis.Skeletons]: "Skeletons",
  [minis.Sneed]: "Sneed",
  [minis.Spiderlings]: "Spiderlings",
  [minis.StonehoofTauren]: "Stonehoof Tauren",
  [minis.SwoleTroll]: "Swole Troll",
  [minis.SylvanasWindrunner]: "Sylvanas Windrunner",
  [minis.TirionFordring]: "Tirion Fordring",
  [minis.Treant]: "Treant",
  [minis.Vultures]: "Vultures",
  [minis.WarsongGrunts]: "Warsong Grunts",
  [minis.WarsongRaider]: "Warsong Raider",
  [minis.WhelpEggs]: "Whelp Eggs",
  [minis.WitchDoctor]: "Witch Doctor",
  [minis.Worgen]: "Worgen",
  [minis.YseraTheDreamer]: "Ysera, The Dreamer",
  [minis.Priestess]: "Priestess",
  [minis.ArthasMenethil]: "Arthas Menethil",
} as const;

const allMinis = Object.values(minis).reduce((hash, id) => {
  const mini = {
    id,
    name: getMiniName(id),
    availableTalents: getTalentsForMini(id),
  };

  return { ...hash, [id]: mini };
}, {} as Record<string, Mini>);

export function getMiniDefinition(miniId: MiniId | number) {
  return allMinis[miniId as MiniId];
}

export function getMiniName(miniId: MiniId | number) {
  return names[miniId as MiniId] ?? "Unknown mini";
}
